server:
  name: go-app-server
  listen: :8080
  # s
  shutdownTimeout: 30
log:
  filename: logs/app.log
  # M
  maxSize: 1024
  # Day
  maxAge: 10
  level: debug
  reportCaller: false
  outputToConsole: true
db:
  # user:password , timeout for connection timeout
  dsn: '%s:%s@tcp(127.0.0.1:3306)/app_db?charset=utf8mb4&parseTime=True&loc=Local&timeout=6s&readTimeout=60s&clientFoundRows=true'
  user: root
  password: 12345678
  maxOpenConns: 10
  maxIdleConns: 1
  # s
  connMaxLifetime: 3600
  # s
  connMaxIdleTime: 600